#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    x=len(arr);
    lsum=0
    rsum=0
    for i in range(0,x):
        for j in range(0,x):
            if(i==j):
                lsum=lsum+arr[i][j];
            if((i+j)==(x-1)):
                rsum=rsum+arr[i][j]
    sum=lsum-rsum
    if(sum<0):
        sum=sum*(-1)
    return sum;
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
