#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    arr.sort()
    minsum=0
    maxsum=0
    for i in range(1,len(arr)):
        maxsum=maxsum+arr[i]
    j=0
    while(j<len(arr)-1):
        minsum=minsum+arr[j]
        j=j+1
    
    print(minsum,maxsum)


if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
