#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    Matrix = [[0 for x in range(n)] for y in range(n)] 
    for i in range(0,n):
        for j in range(0,n):
            if((i+j)>=(n-1)):
                Matrix[i][j]="#"
            else:
                Matrix[i][j]=" "
    print(Matrix)
    for i in Matrix:
        print
if __name__ == '__main__':
    n = int(input())

    staircase(n)
